pipeline {
    agent any

    parameters {
        choice(name: 'ACTION', choices: ['plan', 'apply', 'destroy'], description: 'Choose the Terraform action to perform')
    }

    stages {
        stage('Initialize VPC') {
            steps {
                dir('eks-install/modules/vpc') {
                    script {
                        sh "terraform init"
                    }
                }
            }
        }

        stage('Plan VPC') {
            when {
                expression { params.ACTION == 'plan' }
            }
            steps {
                dir('eks-install/modules/vpc') {
                    script {
                        sh "terraform plan -var-file=../../../variables.tf"
                    }
                }
            }
        }

        stage('Apply VPC') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                dir('eks-install/modules/vpc') {
                    script {
                        sh "terraform apply -auto-approve -var-file=../../../variables.tf"
                    }
                }
            }
        }

        stage('Destroy VPC') {
            when {
                expression { params.ACTION == 'destroy' }
            }
            steps {
                dir('eks-install/modules/vpc') {
                    script {
                        sh "terraform destroy -auto-approve -var-file=../../../variables.tf"
                    }
                }
            }
        }

        stage('Initialize EKS') {
            steps {
                dir('eks-install/modules/eks') {
                    script {
                        sh "terraform init"
                    }
                }
            }
        }

        stage('Plan EKS') {
            when {
                expression { params.ACTION == 'plan' }
            }
            steps {
                dir('eks-install/modules/eks') {
                    script {
                        sh "terraform plan -var-file=../../../variables.tf"
                    }
                }
            }
        }

        stage('Apply EKS') {
            when {
                expression { params.ACTION == 'apply' }
            }
            steps {
                dir('eks-install/modules/eks') {
                    script {
                        sh "terraform apply -auto-approve -var-file=../../../variables.tf"
                    }
                }
            }
        }

        stage('Destroy EKS') {
            when {
                expression { params.ACTION == 'destroy' }
            }
            steps {
                dir('eks-install/modules/eks') {
                    script {
                        sh "terraform destroy -auto-approve -var-file=../../../variables.tf"
                    }
                }
            }
        }
    }
}
