pipeline{
    agent any
     parameters {
       choice(name: 'ACTION', choices: ['plan', 'apply', 'destroy'], description: 'select the action') 
     }
    stages{
        stage('git clone') { 
            steps {
                checkout scmGit(branches: [[name: '*/main]], extensions: [], userRemoteConfigs: [['url: 'https://github.com/PrashanthMunigala/mydemoapp.git']])
                } 
            }
        }
        stage('Terraform init') {
           steps {
                 sh 'terraform init' 
           }
        }
        stage('terraform plan') {
            when {
                expression { return params.ACTION == 'plan' }
            }
            steps {
                    sh 'terraform plan'
            }
        }
        stage('terraform validate') {
            steps {
                    sh 'terraform validate'
            }
        }
        stage('Terraform apply') {
            when {
                expression { return params.ACTION == 'apply' }
            }
            steps { 
                  sh 'terraform apply -auto-approve'
            }
        }
        stage('terraform destroy') {
            when {
                expression { return params.ACTION == 'destroy' }
            }
            steps {
                    sh 'terraform destroy -auto-approve'
            }
        }
}
